### ISSUE TITLE
Investigate spatial joining

### ISSUE THREAD

**Issue by nathancday** [Smart-Cville/cville-airbnb#5]
Airbnb scrap is in lat/lon coordinates, but the city's permit data is likely by address. How do we get these two together?

**Comment by courtney-whalen** [comment]
Added a notebook here: https://github.com/Smart-Cville/cville-airbnb/blob/master/scrapy-splash/spatial-join.ipynb

A couple options to join AirBnB data to City data:

1. Reverse-geocoding - Convert AirBnB coordinates to address & join on address
- OpenStreetMap geocoder is free, but for many rows, it doesn't get more detailed than street name
- Other geocoders (i.e. GoogleV3) may be better, but I think you have to pay for these?
2. Geocoding - Convert City address to coordinates & join on coordinates
- Will need to add a buffer & join city data to AirBnB data if points are within a small distance (25 meters?)
- Will be an issue with apartments or properties really close together
